---
galaxy_info:
  author: arenui
  description: Configure ansible-pull systemd timer
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm

  galaxy_tags:
    - ansible
    - pull
    - gitops
    - systemd

dependencies: []
